version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "monthly"
    assignees:
      - Gustry

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - Gustry
