# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_queries.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_ui_my_queries(object):
    def setupUi(self, ui_my_queries):
        ui_my_queries.setObjectName("ui_my_queries")
        ui_my_queries.resize(727, 794)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ui_my_queries.sizePolicy().hasHeightForWidth())
        ui_my_queries.setSizePolicy(sizePolicy)
        ui_my_queries.setMinimumSize(QtCore.QSize(225, 262))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_my_queries)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_my_queries)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 786))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout.addWidget(self.lineEdit_search)
        self.treeQueries = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        self.treeQueries.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeQueries.setColumnCount(1)
        self.treeQueries.setObjectName("treeQueries")
        self.treeQueries.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeQueries)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setText("{{geocodeArea:}}")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_nominatim = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_nominatim.setObjectName("lineEdit_nominatim")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nominatim)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText("{{bbox}}")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.radioButton_extentMapCanvas = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_extentMapCanvas.setChecked(True)
        self.radioButton_extentMapCanvas.setObjectName("radioButton_extentMapCanvas")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_extentMapCanvas)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_extentLayer = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_extentLayer.setObjectName("radioButton_extentLayer")
        self.horizontalLayout_5.addWidget(self.radioButton_extentLayer)
        self.comboBox_extentLayer = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_extentLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_extentLayer.setSizePolicy(sizePolicy)
        self.comboBox_extentLayer.setObjectName("comboBox_extentLayer")
        self.horizontalLayout_5.addWidget(self.comboBox_extentLayer)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.groupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setText("Points")
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_points = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_points.setText("")
        self.checkBox_points.setChecked(True)
        self.checkBox_points.setObjectName("checkBox_points")
        self.horizontalLayout_4.addWidget(self.checkBox_points)
        self.lineEdit_csv_points = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_csv_points.setInputMask("")
        self.lineEdit_csv_points.setText("")
        self.lineEdit_csv_points.setPlaceholderText("col1,col2,col3")
        self.lineEdit_csv_points.setObjectName("lineEdit_csv_points")
        self.horizontalLayout_4.addWidget(self.lineEdit_csv_points)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_lines = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_lines.setText("")
        self.checkBox_lines.setChecked(True)
        self.checkBox_lines.setObjectName("checkBox_lines")
        self.horizontalLayout_6.addWidget(self.checkBox_lines)
        self.lineEdit_csv_lines = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_csv_lines.setObjectName("lineEdit_csv_lines")
        self.horizontalLayout_6.addWidget(self.lineEdit_csv_lines)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setText("Lines")
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_multilinestrings = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_multilinestrings.setText("")
        self.checkBox_multilinestrings.setChecked(True)
        self.checkBox_multilinestrings.setObjectName("checkBox_multilinestrings")
        self.horizontalLayout_7.addWidget(self.checkBox_multilinestrings)
        self.lineEdit_csv_multilinestrings = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_csv_multilinestrings.setPlaceholderText("")
        self.lineEdit_csv_multilinestrings.setObjectName("lineEdit_csv_multilinestrings")
        self.horizontalLayout_7.addWidget(self.lineEdit_csv_multilinestrings)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setText("Multilinestrings")
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_multipolygons = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_multipolygons.setText("")
        self.checkBox_multipolygons.setChecked(True)
        self.checkBox_multipolygons.setObjectName("checkBox_multipolygons")
        self.horizontalLayout_8.addWidget(self.checkBox_multipolygons)
        self.lineEdit_csv_multipolygons = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_csv_multipolygons.setPlaceholderText("")
        self.lineEdit_csv_multipolygons.setObjectName("lineEdit_csv_multipolygons")
        self.horizontalLayout_8.addWidget(self.lineEdit_csv_multipolygons)
        self.formLayout_4.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setText("Multipolygons")
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_browseDir = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_browseDir.setObjectName("lineEdit_browseDir")
        self.horizontalLayout.addWidget(self.lineEdit_browseDir)
        self.pushButton_browse_output_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_browse_output_file.setObjectName("pushButton_browse_output_file")
        self.horizontalLayout.addWidget(self.pushButton_browse_output_file)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_showQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_showQuery.setObjectName("pushButton_showQuery")
        self.horizontalLayout_3.addWidget(self.pushButton_showQuery)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setDefault(True)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.horizontalLayout_3.addWidget(self.pushButton_runQuery)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setText("text progress")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_my_queries)
        self.checkBox_points.toggled['bool'].connect(self.lineEdit_csv_points.setEnabled)
        self.checkBox_lines.toggled['bool'].connect(self.lineEdit_csv_lines.setEnabled)
        self.checkBox_multilinestrings.toggled['bool'].connect(self.lineEdit_csv_multilinestrings.setEnabled)
        self.checkBox_multipolygons.toggled['bool'].connect(self.lineEdit_csv_multipolygons.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ui_my_queries)

    def retranslateUi(self, ui_my_queries):
        _translate = QtCore.QCoreApplication.translate
        ui_my_queries.setWindowTitle(_translate("ui_my_queries", "QuickOSM - My queries"))
        self.lineEdit_search.setPlaceholderText(_translate("ui_my_queries", "Search"))
        self.treeQueries.setSortingEnabled(False)
        self.treeQueries.headerItem().setText(0, _translate("ui_my_queries", "Query"))
        self.radioButton_extentMapCanvas.setText(_translate("ui_my_queries", "Extent of the map canvas"))
        self.radioButton_extentLayer.setText(_translate("ui_my_queries", "Extent of a layer"))
        self.groupBox.setTitle(_translate("ui_my_queries", "Advanced"))
        self.label_3.setText(_translate("ui_my_queries", "Outputs"))
        self.lineEdit_csv_lines.setPlaceholderText(_translate("ui_my_queries", "or let empty"))
        self.label_4.setText(_translate("ui_my_queries", "Directory"))
        self.lineEdit_browseDir.setPlaceholderText(_translate("ui_my_queries", "Save to temporary file"))
        self.pushButton_browse_output_file.setText(_translate("ui_my_queries", "Browse"))
        self.label_6.setText(_translate("ui_my_queries", "File prefix"))
        self.pushButton_showQuery.setText(_translate("ui_my_queries", "Show query"))
        self.pushButton_runQuery.setText(_translate("ui_my_queries", "Run query"))

from qgis.gui import QgsCollapsibleGroupBox
from qgis.gui import QgsMapLayerComboBox
