# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/osm_file.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_osm_file(object):
    def setupUi(self, ui_osm_file):
        ui_osm_file.setObjectName("ui_osm_file")
        ui_osm_file.resize(589, 408)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_osm_file)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_osm_file)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 411))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_osmFile = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_osmFile.setObjectName("lineEdit_osmFile")
        self.horizontalLayout.addWidget(self.lineEdit_osmFile)
        self.pushButton_browseOsmFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_browseOsmFile.setObjectName("pushButton_browseOsmFile")
        self.horizontalLayout.addWidget(self.pushButton_browseOsmFile)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText("Points")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.checkBox_points = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_points.setText("")
        self.checkBox_points.setChecked(True)
        self.checkBox_points.setObjectName("checkBox_points")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_points)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setText("Lines")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.checkBox_lines = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_lines.setText("")
        self.checkBox_lines.setChecked(True)
        self.checkBox_lines.setObjectName("checkBox_lines")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_lines)
        self.checkBox_multilinestrings = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_multilinestrings.setText("")
        self.checkBox_multilinestrings.setChecked(True)
        self.checkBox_multilinestrings.setObjectName("checkBox_multilinestrings")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_multilinestrings)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText("Multipolygons")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBox_multipolygons = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_multipolygons.setText("")
        self.checkBox_multipolygons.setChecked(True)
        self.checkBox_multipolygons.setObjectName("checkBox_multipolygons")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_multipolygons)
        self.radioButton_allTags = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_allTags.setChecked(True)
        self.radioButton_allTags.setObjectName("radioButton_allTags")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.radioButton_allTags)
        self.groupBox_file = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_file.setTitle("")
        self.groupBox_file.setObjectName("groupBox_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_file)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_file)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_browseDir = QtWidgets.QLineEdit(self.groupBox_file)
        self.lineEdit_browseDir.setObjectName("lineEdit_browseDir")
        self.horizontalLayout_3.addWidget(self.lineEdit_browseDir)
        self.pushButton_browse_output_file = QtWidgets.QPushButton(self.groupBox_file)
        self.pushButton_browse_output_file.setObjectName("pushButton_browse_output_file")
        self.horizontalLayout_3.addWidget(self.pushButton_browse_output_file)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_file)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.groupBox_file)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.groupBox_file)
        self.radioButton_osmConf = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_osmConf.setChecked(False)
        self.radioButton_osmConf.setObjectName("radioButton_osmConf")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.radioButton_osmConf)
        self.horizontalLayout_osmConf = QtWidgets.QHBoxLayout()
        self.horizontalLayout_osmConf.setObjectName("horizontalLayout_osmConf")
        self.lineEdit_osmConf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_osmConf.setObjectName("lineEdit_osmConf")
        self.horizontalLayout_osmConf.addWidget(self.lineEdit_osmConf)
        self.pushButton_browseOsmConf = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_browseOsmConf.setObjectName("pushButton_browseOsmConf")
        self.horizontalLayout_osmConf.addWidget(self.pushButton_browseOsmConf)
        self.pushButton_resetIni = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_resetIni.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_resetIni.setIcon(icon)
        self.pushButton_resetIni.setObjectName("pushButton_resetIni")
        self.horizontalLayout_osmConf.addWidget(self.pushButton_resetIni)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_osmConf)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText("Multilinestrings")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.verticalLayout.addWidget(self.pushButton_runQuery)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setText("text progress")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_osm_file)
        self.radioButton_allTags.toggled['bool'].connect(self.groupBox_file.setEnabled)
        self.radioButton_osmConf.toggled['bool'].connect(self.lineEdit_osmConf.setEnabled)
        self.radioButton_osmConf.toggled['bool'].connect(self.pushButton_browseOsmConf.setEnabled)
        self.radioButton_osmConf.toggled['bool'].connect(self.pushButton_resetIni.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ui_osm_file)

    def retranslateUi(self, ui_osm_file):
        _translate = QtCore.QCoreApplication.translate
        ui_osm_file.setWindowTitle(_translate("ui_osm_file", "QuickOSM - OSM File"))
        self.label.setText(_translate("ui_osm_file", "OSM File"))
        self.pushButton_browseOsmFile.setText(_translate("ui_osm_file", "Browse"))
        self.radioButton_allTags.setText(_translate("ui_osm_file", "All tags"))
        self.label_2.setText(_translate("ui_osm_file", "Directory"))
        self.lineEdit_browseDir.setPlaceholderText(_translate("ui_osm_file", "Save to temporary file"))
        self.pushButton_browse_output_file.setText(_translate("ui_osm_file", "Browse"))
        self.label_7.setText(_translate("ui_osm_file", "File prefix"))
        self.radioButton_osmConf.setText(_translate("ui_osm_file", "OSMConf"))
        self.pushButton_browseOsmConf.setText(_translate("ui_osm_file", "Browse"))
        self.pushButton_runQuery.setText(_translate("ui_osm_file", "Open"))

