# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/osm_file.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_osm_file(object):
    def setupUi(self, ui_osm_file):
        ui_osm_file.setObjectName("ui_osm_file")
        ui_osm_file.resize(589, 408)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_osm_file)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_osm_file)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 571, 390))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.osm_file = QgsFileWidget(self.scrollAreaWidgetContents)
        self.osm_file.setObjectName("osm_file")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.osm_file)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText("Points")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.checkBox_points = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_points.setText("")
        self.checkBox_points.setChecked(True)
        self.checkBox_points.setObjectName("checkBox_points")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_points)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setText("Lines")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.checkBox_lines = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_lines.setText("")
        self.checkBox_lines.setChecked(True)
        self.checkBox_lines.setObjectName("checkBox_lines")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_lines)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText("Multilinestrings")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.checkBox_multilinestrings = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_multilinestrings.setText("")
        self.checkBox_multilinestrings.setChecked(True)
        self.checkBox_multilinestrings.setObjectName("checkBox_multilinestrings")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_multilinestrings)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText("Multipolygons")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBox_multipolygons = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_multipolygons.setText("")
        self.checkBox_multipolygons.setChecked(True)
        self.checkBox_multipolygons.setObjectName("checkBox_multipolygons")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_multipolygons)
        self.radioButton_allTags = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_allTags.setChecked(True)
        self.radioButton_allTags.setObjectName("radioButton_allTags")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.radioButton_allTags)
        self.groupBox_file = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_file.setTitle("")
        self.groupBox_file.setObjectName("groupBox_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_file)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_file)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.output_directory = QgsFileWidget(self.groupBox_file)
        self.output_directory.setObjectName("output_directory")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.output_directory)
        self.label_7 = QtWidgets.QLabel(self.groupBox_file)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.groupBox_file)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.groupBox_file)
        self.radioButton_osmConf = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_osmConf.setChecked(False)
        self.radioButton_osmConf.setObjectName("radioButton_osmConf")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.radioButton_osmConf)
        self.osm_conf = QgsFileWidget(self.scrollAreaWidgetContents)
        self.osm_conf.setObjectName("osm_conf")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.osm_conf)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.verticalLayout.addWidget(self.pushButton_runQuery)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setText("text progress")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_osm_file)
        self.radioButton_allTags.toggled['bool'].connect(self.groupBox_file.setEnabled)
        self.radioButton_osmConf.toggled['bool'].connect(self.osm_conf.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ui_osm_file)

    def retranslateUi(self, ui_osm_file):
        _translate = QtCore.QCoreApplication.translate
        ui_osm_file.setWindowTitle(_translate("ui_osm_file", "QuickOSM - OSM File"))
        self.label.setText(_translate("ui_osm_file", "OSM File"))
        self.radioButton_allTags.setText(_translate("ui_osm_file", "All tags"))
        self.label_2.setText(_translate("ui_osm_file", "Directory"))
        self.label_7.setText(_translate("ui_osm_file", "File prefix"))
        self.radioButton_osmConf.setText(_translate("ui_osm_file", "OSMConf"))
        self.pushButton_runQuery.setText(_translate("ui_osm_file", "Open"))

from qgis.gui import QgsFileWidget
